voidclam:
  size2rangemultiplier: 4.0
  trapintruders: true
  killintruders: false
  maxclamsize: 15
  lightseekmode: "randomweighted"
  seekrangemult: 4
  energypersizetogrow: 4

  vol_heartbeat: 5
  pitch_heartbeat: 0.01
  ticks_heartbeat: 100

  vol_buildpath: 5
  pitch_buildpath: 0.01
  ticks_buildpath: 20

  ticks_lightseek: 100

  ticks_repairgrow: 12000