name: voidclam
version: '1.0-SNAPSHOT'
main: org.serbanstein.voidclam.Main
api-version: '1.20'
# Replace "kit" with the name of your command.
commands:
  createvoidclam:
    description: Create a voidclam at x y z in your world
    usage: /<command> <x> <y> <z>
    permission: voidclam.create

  listclams:
    description: List all voidclams in your world
    usage: /<command>
    permission: voidclam.list

  tickrepairgrow:
    description: Trigger repair/grow check
    usage: /<command>
    permission: voidclam.tickrepairgrow

  forcegrow:
    description: Force a voidclam to increase size by 1
    usage: /<command> <id>
    permission: voidclam.forcegrow